FROM docker.io/alpine:latest

RUN apk update
RUN apk add --no-cache --update musl musl-utils musl-locales tzdata

RUN echo 'export LC_ALL=en_GB.UTF-8' >> /etc/profile.d/locale.sh && \
  sed -i 's|LANG=C.UTF-8|LANG=en_GB.UTF-8|' /etc/profile.d/locale.sh

RUN echo 'export LC_ALL=it_IT.UTF-8' >> /etc/profile.d/locale.sh && \
  sed -i 's|LANG=C.UTF-8|LANG=it_IT.UTF-8|' /etc/profile.d/locale.sh

RUN apk add openssh bash xrdp xorgxrdp xorg-server adwaita-icon-theme\
  xfce4-terminal firefox openbox thunar font-dejavu

RUN echo -e "#!/bin/sh\nexec openbox-session" > /etc/X11/xinit/xinitrc.d/openbox
RUN chmod +x /etc/X11/xinit/xinitrc.d/openbox

RUN echo -e "rdesktop\nrdesktop" | passwd

COPY ./menu.xml /etc/xdg/openbox/menu.xml

COPY ./ct-entrypoint.sh /usr/local/bin/ct-entrypoint
RUN chmod +x /usr/local/bin/ct-entrypoint
ENTRYPOINT /usr/local/bin/ct-entrypoint