FROM docker.io/alpine:latest

RUN apk update && \
    apk add --no-cache --update python3 pipx ffmpeg && \
    adduser -D -u 1000 default

WORKDIR /home/default
USER default

RUN pipx install disopy

COPY --chown=default ./disopy.json /home/default/.config/disopy/

ENTRYPOINT ["/home/default/.local/bin/disopy"]
