FROM docker.io/alpine:latest as base

# Build-time arguments
ARG REPO_URL

# Metadata according to OCI standards
LABEL org.opencontainers.image.title="Alpine RDP Desktop"
LABEL org.opencontainers.image.description="Lightweight DE with RDP access"
LABEL org.opencontainers.image.authors="Giuseppe Rocco"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source=$REPO_URL

# 1. Install packages
# 2. Generate a dbus machine-id
# 3. Purge caches and temporary files
RUN apk update && \
    apk add --no-cache --update \
    sudo \
    musl \
    musl-utils \
    musl-locales \
    openssh \
    openssl \
    xrdp \
    xorgxrdp \
    xorg-server \
    xfce4 \
    faenza-icon-theme \
    xfce4-terminal \
    firefox \
    nano && \
    echo -e "#!/bin/sh\nexec startxfce4" > /etc/X11/xinit/xinitrc.d/xfce4 && \
    chmod +x /etc/X11/xinit/xinitrc.d/xfce4 && \
    dbus-uuidgen > /var/lib/dbus/machine-id && \
    rm -rf /tmp/* /var/tmp/* /var/cache/apk/*

# Copying the container entrypoint script, then setting +x perm
# (ensure the file is in the same directory as the Containerfile)
COPY ./ct-entrypoint.sh /usr/local/bin/ct-entrypoint
RUN chmod +x /usr/local/bin/ct-entrypoint

# Create a non-root user with sudo privileges
RUN adduser -D -u 1000 default && \
    echo "default ALL=NOPASSWD:ALL" > /etc/sudoers.d/default

USER default
WORKDIR /home/default

# RDP default port
EXPOSE 3389/tcp

ENTRYPOINT ["/usr/local/bin/ct-entrypoint"]

