FROM docker.io/alpine:latest as base

RUN apk update && \
    apk add --no-cache --update \
    sudo \
    musl \
    musl-utils \
    musl-locales \
    openssh \
    openssl \
    xrdp \
    xorgxrdp \
    xorg-server \
    xfce4 \
    faenza-icon-theme \
    xfce4-terminal \
    firefox \
    nano && \
    echo -e "#!/bin/sh\nexec startxfce4" > /etc/X11/xinit/xinitrc.d/xfce4 && \
    chmod +x /etc/X11/xinit/xinitrc.d/xfce4 && \
    dbus-uuidgen > /var/lib/dbus/machine-id && \
    rm -rf /tmp/* /var/tmp/* /var/cache/apk/*

RUN adduser -D -u 1000 default && \
    echo "default ALL=NOPASSWD:ALL" > /etc/sudoers.d/default

COPY ./ct-entrypoint.sh /usr/local/bin/ct-entrypoint
RUN chmod +x /usr/local/bin/ct-entrypoint

USER default
WORKDIR /home/default

EXPOSE 3389/tcp
ENTRYPOINT ["/usr/local/bin/ct-entrypoint"]

