FROM docker.io/archlinux:base-devel

RUN pacman-key --init

RUN useradd -m default
RUN echo "default ALL=NOPASSWD:ALL" > /etc/sudoers.d/default
RUN install -o default -g default -d /run/user/1000
WORKDIR /home/default
USER default

RUN sudo pacman -Sy --noconfirm sudo git

RUN git clone https://aur.archlinux.org/uxplay.git

WORKDIR /home/default/uxplay

RUN makepkg -si --noconfirm --needed

WORKDIR /home/default

RUN pacman -Qdtq | sudo pacman -Rcns --noconfirm -
RUN sudo pacman -Sc --noconfirm
RUN rm -fr /home/default/uxplay

ENV XDG_RUNTIME_DIR /run/user/1000

ENTRYPOINT uxplay