FROM docker.io/archlinux:latest
RUN pacman-key --init && \
    pacman -Syyu --noconfirm base-devel sudo git pipewire \
        wireplumber pipewire-alsa pipewire-jack alsa-utils

RUN useradd -u 1000 -m default && \
    echo "default ALL=NOPASSWD:ALL" > /etc/sudoers.d/default && \
    install -o default -g default -d /run/user/1000

WORKDIR /home/default
USER default

RUN git clone https://aur.archlinux.org/uxplay.git && \
    cd uxplay && \
    makepkg -si --noconfirm --needed --rmdeps --clean && \
    cd && \
    rm -fr uxplay

RUN sudo pacman -Rcns git base-devel --noconfirm && \
    sudo pacman -Scc --noconfirm

ENV XDG_RUNTIME_DIR /run/user/1000

ENTRYPOINT ["/usr/bin/uxplay"]