FROM docker.io/library/debian:stable-slim as base

# Build-time arguments
ARG REPO_URL

# Metadata according to OCI standards
LABEL org.opencontainers.image.title="Podman"
LABEL org.opencontainers.image.description="Lightweight Podman image with SSH server"
LABEL org.opencontainers.image.authors="Giuseppe Rocco"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.source=$REPO_URL

# Install the bare minimum to get podman and sshd working
# Having nano installed is just a convenience for interactive shells
RUN apt update && \
    apt install --no-install-recommends --yes \
    nano \
    ca-certificates \
    openssh-server \
    libcap2-bin \
    uidmap \
    fuse-overlayfs \
    nftables \
    buildah \
    aardvark-dns \
    netavark \
    passt \
    podman \
    podman-compose && \
    apt clean && rm -rf /var/lib/apt/lists/* && \
    setcap 'cap_net_bind_service=+ep' /usr/sbin/sshd

# 1. Create a non-root user without privilege escalation and empty password
# 2. Setup rootless sub-uid/gid mapping according to RedHat's podman-in-podman docs
RUN useradd -U -u 1000 -m podman -s /usr/bin/bash && \
    passwd -d podman && \
    install -o 1000 -g 1000 -d /opt/sshd -m 700 && \
    echo "podman:10000:5000" > /etc/subgid && \
    echo "podman:10000:5000" > /etc/subuid

WORKDIR /home/podman
USER podman

# Generating the server RSA key
RUN ssh-keygen -f /opt/sshd/rsa_key -N '' -t rsa

# Default SSH port outside of reserved range
EXPOSE 22/tcp 

ENTRYPOINT ["/usr/sbin/sshd", "-De", "-o", "HostKey=/opt/sshd/rsa_key", "-o", "PermitEmptyPasswords=yes", "-o", "PidFile=/opt/sshd/sshd.pid"]