FROM docker.io/python:3.11.5

RUN apt update && \
    apt install --yes --no-install-recommends ffmpeg && \
    apt clean

RUN pip install --no-cache-dir disopy

RUN useradd -u 1000 -m default

COPY --chown=default ./config.json /home/default/.config/disopy/disopy.json

USER default
WORKDIR /home/default

ENTRYPOINT disopy
