FROM docker.io/python:3.11.5

RUN apt update

RUN apt install --yes ffmpeg --no-install-recommends

RUN pip install --no-cache-dir disopy

RUN mkdir -p /root/.config/disopy

COPY ./config.json /root/.config/disopy/disopy.json

CMD ["disopy"]
