FROM docker.io/alpine:latest as STAGE1

WORKDIR /root

RUN apk update && \
    apk add --no-cache --update \
        build-base git cmake pkgconfig \
        libx11-dev openssl-dev libplist-dev avahi-dev \
        gstreamer-dev gst-plugins-base-dev

RUN git clone https://github.com/FDH2/UxPlay.git && \
    mkdir build && cd build && cmake ../UxPlay && make

FROM docker.io/alpine:latest

COPY --from=STAGE1 /root/build/uxplay /usr/local/bin/uxplay

RUN apk update && \
    apk add --no-cache --update openssl libplist avahi avahi-compat-libdns_sd \
                gst-plugins-base gst-plugins-good gst-plugins-bad gst-libav \
                wireplumber pipewire pipewire-alsa alsa-utils && \
    adduser -D -u 1000 default && \
    install -o default -g default -d /run/user/1000

ENV XDG_RUNTIME_DIR /run/user/1000

WORKDIR /home/default
USER default

ENTRYPOINT ["/usr/local/bin/uxplay"]