name: uxplay

on:
  push:
    branches:
      - master
    paths:
      - uxplay/**
      - '!uxplay/README.md'
  pull_request:
    branches:
      - master
    paths:
      - uxplay/**
      - '!uxplay/README.md'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Docker
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Build the image
    - name: Build the Docker image
      run: |
        REPO_NAME=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
        cd uxplay && docker build -t ghcr.io/$REPO_NAME/uxplay:latest . --file Containerfile

    # Step 4: Push the Docker image
    - name: Push Docker Image
      run: |
        REPO_NAME=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/$REPO_NAME/uxplay:latest
